module.exports = {
  extends: ['../config.js'],
  rules: {
    'array-bracket-newline': ['error', 'consistent'],
    'array-bracket-spacing': ['error', 'never'],
    'array-element-newline': 'off',
    'block-spacing': 'off',
    'brace-style': 'off',
    'camelcase': ['error', { 'properties': 'always' }],
    'capitalized-comments': 'off',
    'comma-dangle': ['error', 'never'],
    'comma-spacing': 'off',
    'comma-style': ['error', 'last'],
    'computed-property-spacing': ['error', 'never'],
    'consistent-this': 'off',
    'eol-last': ['error', 'always'],
    'func-call-spacing': ['error', 'never'],
    'func-name-matching': 'error',
    'func-names': 'error',
    'func-style': 'off',
    'function-call-argument-newline': 'off',
    'function-paren-newline': 'off',
    'id-denylist': 'off',
    'id-length': 'off',
    'id-match': ['error', '^\\$?(__)?(([A-Z]|[a-z]|[0-9]+)|([A-Z_]))*\\$?$'],
    'implicit-arrow-linebreak': ['error', 'beside'],
    'indent': 'off',
    'jsx-quotes': ['error', 'prefer-single'],
    'key-spacing': [
      'error',
      { 'beforeColon': false, 'afterColon': true, 'mode': 'strict' }
    ],
    'keyword-spacing': ['error', { 'before': true }],
    'line-comment-position': 'off',
    'linebreak-style': ['error', 'unix'],
    'lines-around-comment': ['error', { 'beforeBlockComment': true }],
    'lines-between-class-members': 'off',
    'max-depth': ['error', 4],
    'max-len': 'off',
    'max-lines': [
      'error',
      { 'max': 2500, 'skipBlankLines': false, 'skipComments': false }
    ],
    'max-lines-per-function': ['error', 150],
    'max-nested-callbacks': ['error', 7],
    'max-params': ['error', 7],
    'max-statements': ['error', 40],
    'max-statements-per-line': ['error', { max: 1 }],
    'multiline-comment-style': 'off',
    'multiline-ternary': 'off',
    'new-cap': 'error',
    'new-parens': 'off',
    'newline-per-chained-call': ['error', { 'ignoreChainWithDepth': 2 }],
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-continue': 'error',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-mixed-operators': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': ['error', { 'max': 2, 'maxEOF': 0 }],
    'no-negated-condition': 'error',
    'no-nested-ternary': 'off',
    'no-new-object': 'error',
    'no-plusplus': 'off',
    'no-restricted-syntax': ['error', 'WithStatement'],
    'no-tabs': 'off',
    'no-ternary': 'off',
    'no-trailing-spaces': 'error',
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'nonblock-statement-body-position': [
      'error',
      'beside',
      { 'overrides': { 'while': 'below' } }
    ],
    'object-curly-newline': 'off', // TODO dig in
    'object-curly-spacing': 'off', // TODO dig in
    'object-property-newline': 'off', // TODO dig in
    'one-var': ['error', { 'uninitialized': 'always', 'initialized': 'never' }],
    'one-var-declaration-per-line': 'off',
    'operator-assignment': 'off',
    'operator-linebreak': 'off', // TODO dig in
    'padded-blocks': 'off', // TODO dig in
    'padding-line-between-statements': 'off',
    'prefer-exponentiation-operator': 'warn',
    'prefer-object-spread': 'warn',
    'quote-props': ['error', 'consistent'],
    'quotes': 'off',
    'semi': 'off',
    'semi-spacing': 'error',
    'semi-style': 'off',
    'space-before-blocks': 'off', // TODO dig in
    'sort-keys': 'off',
    'sort-vars': 'off',
    'space-infix-ops': 'error',
    'space-unary-ops': 'off', // TODO dig in
    'spaced-comment': ['error', 'always'],
    'switch-colon-spacing': 'off',
    'template-tag-spacing': 'off',
    'unicode-bom': 'off',
    'wrap-regex': 'error'
  }
};
